version: '3.4'

services:
  analyzer_django:
    container_name: analyzer_django
    image: analyzer
    # command: ["gunicorn", "--bind", "0.0.0.0:8200", "app.wsgi:application"]
    command: ["python", "/app/manage.py", "runserver", "0:80"]
    ports:
      - 8201:80
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
    # network_mode: host
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 15m
    environment:
      DEBUG: 'True'
  
  analyzer_redis:
    image: redis
    container_name: analyzer_redis
    volumes: 
      - ./redis:/data
    restart: always
    # network_mode: host
    logging:
      driver: none
  
  analyzer_worker:
    image: analyzer
    container_name: analyzer_worker
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["celery", "-A", "app", "worker", "-l", "info", "--pidfile="]
    restart: always
    # network_mode: host
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 15m
    environment:
      DEBUG: 'True'
  
  analyzer_beat:
    image: analyzer
    container_name: analyzer_beat
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["celery", "-A", "app", "beat", "-l", "info", "--pidfile="]
    restart: always
    # network_mode: host
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 15m
    environment:
      DEBUG: 'True'
  
networks:
  default:
    external:
      name: army
