version: '3.4'

services:
  crawler:
    image: analyzer
    container_name: analyzer_django
    # command: ["gunicorn", "--bind", "0.0.0.0:8200", "app.wsgi:application"]
    command: ["python", "/app/manage.py", "runserver", "0:80"]
    ports:
      - 8201:80
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    restart: unless-stopped
    # network_mode: host
    environment:
      DEBUG: 'True'
  
  redis:
    image: redis
    container_name: analyzer_redis
    volumes: 
      - ./redis:/data
    restart: always
    # network_mode: host
    logging:
      driver: none
  
  celery_worker:
    image: analyzer
    container_name: analyzer_celery_worker
    volumes:
      - .:/app
    command: ["celery", "-A", "app", "worker", "-l", "info", "--pidfile="]
    restart: always
    # network_mode: host
    # logging:
    #   driver: none
    environment:
      DEBUG: 'True'
  
  celery_scheduler:
    image: analyzer
    container_name: analyzer_celery_scheduler
    volumes:
      - .:/app
    command: ["celery", "-A", "app", "beat", "-l", "info", "--pidfile="]
    restart: always
    # network_mode: host
    # logging:
    #   driver: none
    environment:
      DEBUG: 'True'
  
  
      
