version: '3.4'

services:
  analyzer_django:
    container_name: analyzer_django
    image: analyzer
    command: ["python", "/app/manage.py", "runserver", "0:80"]
    ports:
      - 8201:80
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
  
  analyzer_redis:
    image: redis
    container_name: analyzer_redis
    volumes: 
      - ./redis:/data
    restart: unless-stopped
  
  analyzer_worker:
    image: analyzer
    container_name: analyzer_worker
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["celery", "-A", "app", "worker", "-l", "info", "--pidfile="]
    restart: unless-stopped
  
  analyzer_beat:
    image: analyzer
    container_name: analyzer_beat
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["celery", "-A", "app", "beat", "-l", "info", "--pidfile="]
    restart: always
  
networks:
  default:
    external:
      name: army
