version: '3.4'

services:
  analyzer_django:
    container_name: analyzer_django
    image: analyzer
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "/app/analyzer/manage.py", "runserver", "0:80"]
    ports:
      - 8201:80
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
  
  analyzer_redis:
    image: redis
    container_name: analyzer_redis
    volumes: 
      - ./redis:/data
    restart: unless-stopped
  
  analyzer_worker:
    image: analyzer
    container_name: analyzer_worker
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app/analyzer
    command: ["celery", "-A", "analyzer_app", "worker", "-l", "info", "--pidfile=", "--concurrency=1"]
    restart: unless-stopped
  
  analyzer_beat:
    image: analyzer
    container_name: analyzer_beat
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app/analyzer
    command: ["celery", "-A", "analyzer_app", "beat", "-l", "info", "--pidfile="]
    restart: unless-stopped
  
networks:
  default:
    external:
      name: army
