# Generated by Django 3.0.5 on 2020-05-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0013_related'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'army_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArmyKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'army_keyword',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'category_keyword',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'news_category',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='operation',
            name='summary',
            field=models.BooleanField(default=False),
        ),
    ]
