# Generated by Django 3.0.5 on 2020-05-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_auto_20200522_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
