# Generated by Django 3.0.5 on 2020-05-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0008_ner'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='geo',
            field=models.BooleanField(default=False),
        ),
    ]
