# Generated by Django 3.0.5 on 2020-05-23 01:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0011_sentiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc2vec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', django.contrib.postgres.fields.jsonb.JSONField()),
                ('vector_norm', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'news_vector',
                'managed': False,
            },
        ),
    ]
