# Generated by Django 3.0.5 on 2020-05-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0010_geo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neg', models.FloatField(default=0.0)),
                ('pos', models.FloatField(default=0.0)),
                ('neu', models.FloatField(default=0.0)),
                ('compound', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'news_sentiment',
                'managed': False,
            },
        ),
    ]
